version: "2.4"

services:
    jenkins:
        container_name: Jenkins
        user: root
        image: "jenkinsci/blueocean:1.23.1"
        ports:
            - "1520:8080"
        volumes:
            - disk:/usr/jenkins_home
            - disk:/var/run/docker.sock
        networks:
            - mynet
    db:
        container_name: Julieta
        image: "mysql:5.6.48"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - disk:/usr/mysql
        ports:
            - "3306:3306"
        expose:
            -   "3306"
        environment:
            MYSQL_ROOT_PASSWORD: sad
            MYSQL_DATABASE: misceland
        restart: on-failure
        networks:
            - mynet
    client:
        container_name: Joaquinx
        depends_on:
            - server
        image: "misceland/client"
        ports:
            - "80:80"
        volumes:
            - disk:/etc/nginx/templates
        environment:
            - NGINX_HOST=misceland.com
            - NGINX_PORT=80
        networks:
            - mynet
    server:
        container_name: Jarvis
        depends_on:
            - db
        image: "misceland/server"
        expose:
            -   "9000"
        networks:
            - mynet

networks:
    mynet:
        driver: bridge

volumes:
    disk:
        name: disc0